/**
 * ReyGrid API — TypeScript type definitions.
 * Generated by hand from openapi.yaml (v1.0), schema 3.0.3.
 */

// ---------------------------------------------------------------------------
// Auth / health
// ---------------------------------------------------------------------------

export interface PingMetadata {
  uptime?: number;
  timestamp?: string;
}

export type ServiceStatus = "UP" | "DOWN";

export interface PingResponse {
  success: boolean;
  status: ServiceStatus;
  service: string;
  version: string;
  metadata?: PingMetadata;
}

export interface Usage {
  total: number;
  quotaLimit: number;
}

export interface ValidateResponse {
  success: boolean;
  valid: boolean;
  usage: Usage;
}

// ---------------------------------------------------------------------------
// Errors
// ---------------------------------------------------------------------------

export interface AuthErrorResponse {
  error: string;
  code: string;
}

export interface ValidationErrorItem {
  [key: string]: unknown;
}

export interface ApiError {
  code: string;
  message: string;
  list?: ValidationErrorItem[];
}

export interface ErrorResponse {
  success: boolean;
  error: ApiError;
  /** Present on some error payloads. */
  output?: Record<string, unknown>;
  usage?: ChatUsage;
}

// ---------------------------------------------------------------------------
// Chat / tools
// ---------------------------------------------------------------------------

export interface FunctionDefinition {
  /** Function name, minLength 1 */
  name: string;
  /** Instructions for when the function should be called. */
  instructions?: string;
  /** JSON Schema for the function parameters. */
  parameters?: Record<string, unknown>;
  /** Enforce strict structured output. */
  strict?: boolean;
}

export interface Tool {
  type: "function";
  function: FunctionDefinition;
}

export interface ToolResult {
  toolCallId: string;
  output: string;
}

export interface ChatRequest {
  message: string;
  /**
   * Existing conversation ID. Ignored when userId is provided.
   */
  conversationId?: string;
  /**
   * Stable user identifier for persistent conversations across
   * platforms (WhatsApp, Discord, Telegram). When provided,
   * conversationId is ignored.
   */
  userId?: string;
  /** When true, response is delivered as SSE with delta events. */
  stream?: boolean;
  /** Tool definitions exposed to the agent. */
  tools?: Tool[];
  /** Results of previously-requested tool calls. */
  results?: ToolResult[] | null;
}

export interface Reply {
  id: string;
  content: string;
}

export type FinishReason =
  | "stop"
  | "length"
  | "tool_calls"
  | "content_filter"
  | "canceled"
  | string;

export interface ChatOutput {
  reply: Reply;
  finish_reason: FinishReason;
}

export interface ChatUsage {
  credits: number;
}

export interface ChatResponse {
  success: boolean;
  conversationId?: string;
  userId?: string;
  messageId: string;
  output: ChatOutput;
  usage: ChatUsage;
}

// ---------------------------------------------------------------------------
// Conversations
// ---------------------------------------------------------------------------

export interface Pagination {
  totalPages: number;
  currentPage: number;
  pagingCounter: number;
  hasNextPage: boolean;
}

export interface Conversation {
  conversationId?: string;
  userId?: string;
  messagesCount?: number;
  expiresAt?: string;
  createdAt?: string;
}

export interface ConversationsPagination extends Pagination {
  totalConversations: number;
}

export interface ConversationsResponse {
  success: boolean;
  conversations: Conversation[];
  pagination: ConversationsPagination;
}

// ---------------------------------------------------------------------------
// Messages
// ---------------------------------------------------------------------------

export interface ToolCallFunction {
  name: string;
  arguments: string;
}

export type ToolCallStatus =
  | "pending"
  | "completed"
  | "canceled"
  | "failed"
  | string;

export interface MessageToolCall {
  id: string;
  type: "function";
  function: ToolCallFunction;
  status?: ToolCallStatus;
}

export type MessageRole = "user" | "assistant" | "tool" | "system" | string;

export interface Message {
  id: string;
  content?: string;
  role: MessageRole;
  tool_calls?: MessageToolCall[];
  createdAt: string;
}

export interface MessagesPagination extends Pagination {
  totalMessages: number;
}

export interface MessagesResponse {
  success: boolean;
  userId?: string;
  conversationId?: string;
  messages: Message[];
  pagination: MessagesPagination;
}

// ---------------------------------------------------------------------------
// Deletes / cancel
// ---------------------------------------------------------------------------

export interface DeletedMessages {
  count: number;
}

export interface DeleteMessagesResponse {
  success: boolean;
  deletedMessages: DeletedMessages;
}

export interface CancelToolResponse {
  success: boolean;
  canceled: boolean;
}

// ---------------------------------------------------------------------------
// SSE streaming events (delta events, data-only, no event field)
// ---------------------------------------------------------------------------

/**
 * A single SSE delta frame received during a streaming chat.
 *
 * The API sends data-only messages with this shape:
 * ```json
 * { "success": true, "conversationId": "...", "messageId": "...",
 *   "delta": { "reply": { "content": "..." } }, "usage": { "credits": 0 } }
 * ```
 */
export interface ChatDeltaReply {
  /** Delta fragment of the assistant reply text. */
  content?: string;
  id?: string;
}

export interface ChatDelta {
  /** The reply payload (text fragment). */
  reply?: ChatDeltaReply;
  /** Set on the terminal delta. */
  finish_reason?: FinishReason;
  /** Tool calls delivered as deltas. */
  tool_calls?: MessageToolCall[];
  [key: string]: unknown;
}

export interface ChatDeltaEvent {
  /** Overall stream success — present on first & terminal frames. */
  success?: boolean;
  conversationId?: string;
  messageId?: string;
  /** The delta payload (reply, finish_reason, tool_calls). */
  delta?: ChatDelta;
  /** Present on the terminal frame. */
  usage?: ChatUsage;
  [key: string]: unknown;
}