/**
 * ReyGrid API — TypeScript type definitions.
 * Generated by hand from openapi.yaml (v1.0.3), schema 3.0.3.
 */

// ---------------------------------------------------------------------------
// Auth / health
// ---------------------------------------------------------------------------

export interface PingMetadata {
  uptime?: number;
  timestamp?: string;
}

export type ServiceStatus = "UP" | "DOWN";

export interface PingResponse {
  success: boolean;
  status: ServiceStatus;
  service: string;
  version: string;
  metadata?: PingMetadata;
}

export interface Usage {
  total: number;
  quotaLimit: number;
}

export interface ValidateResponse {
  success: boolean;
  valid: boolean;
  usage: Usage;
}

// ---------------------------------------------------------------------------
// Errors
// ---------------------------------------------------------------------------

export interface AuthErrorResponse {
  error: string;
  code: string;
}

export interface ValidationErrorItem {
  [key: string]: unknown;
}

export interface ApiError {
  code: string;
  message: string;
  list?: ValidationErrorItem[];
}

export interface ErrorResponse {
  success: boolean;
  error: ApiError;
  /** Present on some error payloads. */
  output?: Record<string, unknown>;
  usage?: ChatUsage;
}

// ---------------------------------------------------------------------------
// Chat / tools
// ---------------------------------------------------------------------------

export interface FunctionDefinition {
  /** Function name, minLength 1 */
  name: string;
  /** Instructions for when the function should be called. */
  instructions?: string;
  /** JSON Schema for the function parameters. */
  parameters?: Record<string, unknown>;
  /** Enforce strict structured output. */
  strict?: boolean;
}

export interface Tool {
  type: "function";
  function: FunctionDefinition;
}

export interface ToolResult {
  toolCallId: string;
  output: string;
}

export interface ChatRequest {
  message: string;
  /**
   * Existing conversation ID. Ignored when userId is provided.
   */
  conversationId?: string;
  /**
   * Stable user identifier for persistent conversations across
   * platforms (WhatsApp, Discord, Telegram). When provided,
   * conversationId is ignored.
   */
  userId?: string;
  /** When true, response is delivered as SSE with delta events. */
  stream?: boolean;
  /** Tool definitions exposed to the agent. */
  tools?: Tool[];
  /** Results of previously-requested tool calls. */
  results?: ToolResult[] | null;
}

export interface Reply {
  id: string;
  content: string;
}

export type FinishReason =
  | "stop"
  | "length"
  | "tool_calls"
  | "content_filter"
  | "canceled"
  | string;

export interface ChatOutput {
  reply: Reply;
  finish_reason: FinishReason;
}

export interface ChatUsage {
  credits: number;
}

export interface ChatResponse {
  success: boolean;
  conversationId?: string;
  userId?: string;
  messageId: string;
  output: ChatOutput;
  usage: ChatUsage;
}

// ---------------------------------------------------------------------------
// Conversations
// ---------------------------------------------------------------------------

export interface Pagination {
  totalPages: number;
  currentPage: number;
  pagingCounter: number;
  hasNextPage: boolean;
}

export interface Conversation {
  conversationId?: string;
  userId?: string;
  messagesCount?: number;
  expiresAt?: string;
  createdAt?: string;
}

export interface ConversationsPagination extends Pagination {
  totalConversations: number;
}

export interface ConversationsResponse {
  success: boolean;
  conversations: Conversation[];
  pagination: ConversationsPagination;
}

// ---------------------------------------------------------------------------
// Messages
// ---------------------------------------------------------------------------

export interface ToolCallFunction {
  name: string;
  arguments: string;
}

export type ToolCallStatus =
  | "pending"
  | "completed"
  | "canceled"
  | "failed"
  | string;

export interface MessageToolCall {
  id: string;
  type: "function";
  function: ToolCallFunction;
  status?: ToolCallStatus;
}

export type MessageRole = "user" | "assistant" | "tool" | "system" | string;

export interface Message {
  id: string;
  content?: string;
  role: MessageRole;
  tool_calls?: MessageToolCall[];
  feedback?: Feedback;
  createdAt: string;
}

export interface MessagesPagination extends Pagination {
  totalMessages: number;
}

export interface MessagesResponse {
  success: boolean;
  userId?: string;
  conversationId?: string;
  messages: Message[];
  pagination: MessagesPagination;
}

// ---------------------------------------------------------------------------
// Deletes / cancel
// ---------------------------------------------------------------------------

export interface DeletedMessages {
  count: number;
}

export interface DeleteMessagesResponse {
  success: boolean;
  deletedMessages: DeletedMessages;
}

export interface CancelToolResponse {
  success: boolean;
  canceled: boolean;
}

// ---------------------------------------------------------------------------
// SSE streaming events (delta events, data-only, no event field)
// ---------------------------------------------------------------------------

/**
 * A single SSE delta frame received during a streaming chat.
 *
 * The API sends data-only messages with this shape:
 * ```json
 * { "success": true, "conversationId": "...", "messageId": "...",
 *   "delta": { "reply": { "content": "..." } }, "usage": { "credits": 0 } }
 * ```
 */
export interface ChatDeltaReply {
  /** Delta fragment of the assistant reply text. */
  content?: string;
  id?: string;
}

export interface ChatDelta {
  /** The reply payload (text fragment). */
  reply?: ChatDeltaReply;
  /** Set on the terminal delta. */
  finish_reason?: FinishReason;
  /** Tool calls delivered as deltas. */
  tool_calls?: MessageToolCall[];
  [key: string]: unknown;
}

export interface ChatDeltaEvent {
  /** Overall stream success — present on first & terminal frames. */
  success?: boolean;
  conversationId?: string;
  messageId?: string;
  /** The delta payload (reply, finish_reason, tool_calls). */
  delta?: ChatDelta;
  /** Present on the terminal frame. */
  usage?: ChatUsage;
  [key: string]: unknown;
}

// ---------------------------------------------------------------------------
// Agents
// ---------------------------------------------------------------------------

export interface Agent {
  id: string;
  name: string;
  model: string;
  instructions: string;
  /** Credits spent by the agent so far. */
  usage: number;
  createdAt: string;
}

export interface AgentDetail extends Agent {
  sources: Record<SourceType, number>;
  /** Characters of text plus bytes of files. */
  storage: { used: number; limit: number };
}

export interface AgentUpdate {
  name?: string;
  instructions?: string;
  /** A model ID from `listModels()` that your plan can use. */
  model?: string;
}

export interface AgentsResponse {
  success: boolean;
  agents: Agent[];
}

export interface AgentResponse {
  success: boolean;
  agent: Agent;
}

export interface AgentDetailResponse {
  success: boolean;
  agent: AgentDetail;
}

// ---------------------------------------------------------------------------
// Knowledge sources
// ---------------------------------------------------------------------------

export type SourceType = "text" | "qa" | "file" | "website";

export interface Source {
  id: string;
  type: SourceType;
  /** The title, question, file name or page URL. */
  title: string;
  /** Text or answer. Only for `text` and `qa` sources. */
  content?: string;
  /** File size in bytes. Only for `file` sources. */
  size?: number | null;
  createdAt: string;
}

export interface SourcesPagination extends Pagination {
  totalSources: number;
}

export interface SourcesResponse {
  success: boolean;
  sources: Source[];
  pagination: SourcesPagination;
}

export interface ListSourcesOptions {
  type?: SourceType;
  search?: string;
  page?: number;
  size?: number;
}

export interface SourceCreatedResponse {
  success: boolean;
  source: { id: string; type: SourceType; title: string; size?: number };
}

export interface CrawlResponse {
  success: boolean;
  pagesCrawled: number;
  pages: { id: string; path: string }[];
}

export interface DeleteSourceResponse {
  success: boolean;
  deleted: boolean;
}

// ---------------------------------------------------------------------------
// Search
// ---------------------------------------------------------------------------

export interface SearchResult {
  /** Similarity between 0 and 1. Higher is closer. */
  score: number;
  content: string;
  source: { id: string; type: SourceType; title: string };
}

export interface SearchResponse {
  success: boolean;
  results: SearchResult[];
}

// ---------------------------------------------------------------------------
// Feedback
// ---------------------------------------------------------------------------

export type FeedbackRating = "up" | "down";

export interface Feedback {
  rating: FeedbackRating;
  comment?: string;
  createdAt: string;
}

export interface FeedbackResponse {
  success: boolean;
  feedback: Feedback;
}

// ---------------------------------------------------------------------------
// Models & usage
// ---------------------------------------------------------------------------

export interface Model {
  id: string;
  name: string;
  provider: string;
  /** Credits per message. */
  pricing: number;
  /** Whether your plan can use the model. */
  available: boolean;
}

export interface ModelsResponse {
  success: boolean;
  models: Model[];
}

export interface UsageTotals {
  requests: number;
  failed: number;
  credits: number;
}

export interface UsageReport {
  success: boolean;
  balance: { credits: number; plan: string; renewsAt: string | null };
  period: { days: number; from: string; to: string };
  totals: UsageTotals;
  daily: (UsageTotals & { date: string })[];
  agents: { id: string; name: string | null; requests: number; credits: number }[];
}
